// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcejutzuttpjafwqtxdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZWp1dHp1dHRwamFmd3F0eGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTIzMjMsImV4cCI6MjA1OTc2ODMyM30.RpCSxQsNHfLEgt9gqnl_CchxPH2h1TfGjr-BOXodo2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);